version: '1' 
services:
    mongo: 
        image: mongo 
        ports: 
            - '27017:27017' 
        volumes: 
            - mongodb_data:/data/db  
    api: 
        build: . 
        ports: 
            - '8080:8080' 
        depends_on: 
            - mongo 

volumes: 
    mongodb_data: